[[constraint]]
  name = "github.com/bsm/sarama-cluster"
  version = "2.1.15"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.20.0"

[[constraint]]
  name = "github.com/openfaas-incubator/connector-sdk"
  version = "0.4.2"

[prune]
   go-tests = true
   unused-packages = true
